### ISSUE TITLE
sample config.yaml

### ISSUE THREAD

**Issue by dauwhe** [readium/readium-lcp-server#135]
It would be very helpful to have a relatively complete and functional sample `config.yaml` file somewhere in the repo.

**Comment by danielweck** [comment]
For what it's worth, here's the `config.yaml` I use to test the various HTTP servers on my LAN.
I use a single configuration file for all 3 servers "frontend", "lcp", "led", but bear in mind that a typical real-world deployment (e.g. Docker container instances) would consist in separate / sandboxed server executables, each with their own `config.yaml`.
```yaml
license:
  links:
    hint: "http://192.168.1.67:8989/hint"
    status: "http://192.168.1.67:8990/licenses/{license_id}/status"
    publication: "http://192.168.1.67:8989/contents/{publication_id}"
certificate:
  cert: cert_rsa.pem
  private_key: privkey_rsa.pem
storage:
  filesystem:
    directory: files
localization:
        languages: ["ru-RU", "en-US"]
        folder: messages/
        default_language: "en-US"
lcp:
    host: "192.168.1.67"
    port: 8989
    readonly: false
    public_base_url:  "http://192.168.1.67:8989"
    database: "sqlite3://file:lcp.sqlite?cache=shared&mode=rwc"
    auth_file: "passwords.htpasswd"
    directory: lcpserver/manage
lsd:
    host: "192.168.1.67"
    port: 8990
    readonly: false
    public_base_url:  "http://192.168.1.67:8990"
    database: "sqlite3://file:lsd.sqlite?cache=shared&mode=rwc"
    auth_file: "passwords.htpasswd"
    license_link_url: "http://192.168.1.67:8080/api/v1/purchases/license/{license_id}"
frontend:
    host: "192.168.1.67"
    port: 8080
    readonly: false
    public_base_url:  "http://192.168.1.67:8080"
    database: "sqlite3://file:frontend.sqlite?cache=shared&mode=rwc"
    auth_file: "passwords.htpasswd"
    directory: frontend/manage
    encrypted_repository: /path/to/readium-lcp-server/files
    master_repository: /path/to/readium-lcp-server/epubs
lsd_notify_auth:
    username: daniel
    password: weck
lcp_update_auth:
    username: daniel
    password: weck
license_status:
    renting_days: 10
    renew: true
    renew_days: 3
    return: true
    register: true
```

**Comment by danielweck** [comment]
Split example:

`config.yaml` for "frontend" server:
```yaml
storage:
  filesystem:
    directory: files
lcp:
    public_base_url:  "http://192.168.1.67:8989"
lsd:
    public_base_url:  "http://192.168.1.67:8990"
frontend:
    host: "192.168.1.67"
    port: 8080
    readonly: false
    public_base_url:  "http://192.168.1.67:8080"
    database: "sqlite3://file:frontend.sqlite?cache=shared&mode=rwc"
    directory: frontend/manage
    encrypted_repository: /path/to/readium-lcp-server/files
    master_repository: /path/to/readium-lcp-server/epubs
lcp_update_auth:
    username: daniel
    password: weck
```


`config.yaml` for "lcp" server:
```yaml
license:
  links:
    hint: "http://192.168.1.67:8989/hint"
    status: "http://192.168.1.67:8990/licenses/{license_id}/status"
    publication: "http://192.168.1.67:8989/contents/{publication_id}"
certificate:
  cert: cert_rsa.pem
  private_key: privkey_rsa.pem
storage:
  filesystem:
    directory: files
localization:
        languages: ["ru-RU", "en-US"]
        folder: messages/
        default_language: "en-US"
lcp:
    host: "192.168.1.67"
    port: 8989
    readonly: false
    public_base_url:  "http://192.168.1.67:8989"
    database: "sqlite3://file:lcp.sqlite?cache=shared&mode=rwc"
    auth_file: "passwords.htpasswd"
    directory: lcpserver/manage
lsd:
    public_base_url:  "http://192.168.1.67:8990"
lsd_notify_auth:
    username: daniel
    password: weck
```


`config.yaml` for "lsd" server:
```yaml
localization:
        languages: ["ru-RU", "en-US"]
        folder: messages/
        default_language: "en-US"
lcp:
    public_base_url:  "http://192.168.1.67:8989"
lsd:
    host: "192.168.1.67"
    port: 8990
    readonly: false
    public_base_url:  "http://192.168.1.67:8990"
    database: "sqlite3://file:lsd.sqlite?cache=shared&mode=rwc"
    auth_file: "passwords.htpasswd"
    license_link_url: "http://192.168.1.67:8080/api/v1/purchases/license/{license_id}"
lcp_update_auth:
    username: daniel
    password: weck
license_status:
    renting_days: 10
    renew: true
    renew_days: 3
    return: true
    register: true
```
