### ISSUE TITLE
LSD server fails because `message` folder in config.yaml does not end with slash character.

### ISSUE THREAD

**Issue by danielweck** [readium/readium-lcp-server#39]
```
$ ./lsdserver.exe
panic: open messagesen-US.json: The system cannot find the file specified.
```

YAML config:

``` yaml
localization:
        languages: ["ru-RU", "en-US"]
        folder: messages
```

The issue is fixed by appending a '/' character at the end of the folder location. However, there is no such problem with other YAML configuration parameters, namely:

``` yaml
storage:
  filesystem:
    directory: files
static:
  directory: static
```

I would like to suggest allowing `folder: messages` without the '/' suffix, so that the expected YAML syntax is consistent.

@snemegeer @Boichenko
